server:
  port: ${PORT:8800} # Should be kept unchanged if running in container

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRAR_URL:http://localhost:8761/eureka}
  instance:
    appname: API Gateway service # Just a representational name, not used for routing/load balancing
    #    prefer-ip-address: true
    #    ip-address: ${EUREKA_INSTANCE_IPADDR:127.0.0.1}
    # Accept both hostname & IP address, so setting the 2 above props is unnecessary.
    hostname: ${EUREKA_INSTANCE_HOSTNAME:127.0.0.1}
    # If port is required to be specified, pass these props as program arguments.
    # If not specified, the server's port will be used by default.
#    secure-port-enabled: true
#    secure-port:

rest-service:
  auth:
    name: PROCESSOR-SERVICE
    api:
      verify-token: { method: GET, path: /api/v1/auth/user }
  main-service: { name: MAIN-SERVICE }
  processor: { name: PROCESSOR-SERVICE }
