server:
  port: ${PORT:8800} # Should be kept unchanged if running in container

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRAR_URL:http://localhost:8761/eureka/}

rest-service:
  auth:
    name: PROCESSOR-SERVICE
    api:
      verify-token: { method: GET, path: /api/v1/auth/user }
  main-service: { name: MAIN-SERVICE }
  processor: { name: PROCESSOR-SERVICE }
