server:
  port: ${PORT:8080} # Should be kept unchanged if running in container
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:}

api:
  version: v1
  base-path: "#{'${server.servlet.context-path:}'.length > 0 ? '/${server.servlet.context-path:}' : ''}/api#{'${api.version:}'.length > 0 ? '/${api.version:}' : ''}"

spring:
  application:
    name: Restful project
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 2GB
  datasource:
    url: ${MAIN_DB_URL:jdbc:mysql://localhost:3306/MICROTUBE}
    username: ${MAIN_DB_USERNAME:dbuser}
    password: ${MAIN_DB_PASSWORD:abc123}

  mvc:
    format:
      date-time: iso
  messages: # Alternative config option: create a bean of ReloadableResourceBundleMessageSource
    basename: ${MESSAGES_BASENAME:messages,custom-response-status,errors,error-codes} # name prefix for the file containing message props. Format: config.i18n.messages (dot-separated path names)
    cache-duration: 3600
    encoding: UTF-8
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html # Customize swagger-ui path; didn't work?
    enabled: true
    csrf:
      enabled: true
  api-docs:
    version: openapi_3_1
    enabled: true

application:
  jwt:
    secret: ${JWT_SECRET:htfhvoa+IRypMSVcWbp0gWWkir18RCthewNQh/k/cFM=}
    usage-duration: ${JWT_USAGE_DURATION:120000} # Unit: millisecond

#fluentd:
#  host: ${FLUENTD_HOST:localhost}
#  port: ${FLUENTD_PORT:24224}

management:
  zipkin:
    tracing:
      export:
        enabled: false

video:
  temp-dir: tmp/original-videos/
  result-dir: tmp/result-videos/
