name: microtube
services:
  processor-service:
    image: ${PROCESSOR_SERVICE_IMAGE:-registry.local/microtube/processor-service:latest}
    command:
      - --eureka.instance.non-secure-port=${PUBLISHED_PORT:-8080}
    volumes:
      - ./log:/opt/app/logs
      - ./tmp/:/opt/app/tmp
    networks:
      - microtube-network
    ports:
      - ${PUBLISHED_PORT:-8080}:8080
      - name: actuator
        host_ip: 127.0.0.1
        target: 8081
        published: ${ACTUATOR_PORT:-8081}
        app_protocol: http
#    depends_on:
#      mysql.db:
#        condition: service_healthy
    healthcheck:
      test: sh -c "curl -f http://localhost:8080${SERVER_CONTEXT_PATH-}/healthcheck"
      interval: 20s
      timeout: 10s
      retries: 10
    environment:
      # Application configs
      SPRING_ACTIVES_PROFILE: prod
      SERVER_CONTEXT_PATH: ${SERVER_CONTEXT_PATH-}
      ACTUATOR_HOST: 0.0.0.0
      ACTUATOR_PORT: 8081
      JWT_SECRET: {JWT_SECRET-}
      # Database configs (may put this to .env file)
      MAIN_DB_URL: ${MAIN_DATABASE_URL:-jdbc:mysql://mysql.db:3306/MICROTUBE}
      MAIN_DB_USERNAME: ${DATABASE_USERNAME:-dbuser}
      MAIN_DB_PASSWORD: ${DATABASE_PASSWORD:-123}
      OBJECT_STORE_URL: ${OBJECT_STORE_URL:-http://minio:9000}
      OBJECT_STORE_USERNAME: ${OBJECT_STORE_USERNAME:-admin}
      OBJECT_STORE_PASSWORD: ${OBJECT_STORE_PASSWORD:-minioadmin}
      OBJECT_STORE_BUCKET_TEMP: ${OBJECT_STORE_BUCKET_TEMP:-temporary}
      OBJECT_STORE_BUCKET_HLS: ${OBJECT_STORE_BUCKET_HLS:-hls}
      OBJECT_STORE_BUCKET_AVATAR: ${OBJECT_STORE_BUCKET_AVATAR:-avatar}
      OBJECT_STORE_BUCKET_THUMBNAIL: ${OBJECT_STORE_BUCKET_THUMBNAIL:-thumbnail}
      # Monitoring
#      LOGGING_CONFIG_FILEPATH=/app/config/logback-spring.xml
      FLUENTD_HOST: ${FLUENTD_HOST:-fluentd}
      FLUENTD_PORT: ${FLUENTD_PORT:-24224}
      ENABLE_ZIPKIN: false
      ZIPKIN_ENDPOINT: ${ZIPKIN_ENDPOINT:-http://127.0.0.1:9411/api/v2/spans}
      # Integration
      SERVICE_REGISTRAR_URL: ${SERVICE_REGISTRAR_URL:-http://service-registrar:8761/eureka}
      EUREKA_INSTANCE_HOSTNAME: ${EUREKA_INSTANCE_HOSTNAME:-processor-service}
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: ${FLUENTD_ADDRESS:-localhost:24224}
#        tag: "{{.ImageName}}"
#        fluentd-async:
##        fluentd-async-reconnect-interval: 2s
#        fluentd-buffer-limit: 524288
##        fluentd-retry-wait: 1
##        fluentd-max-retries: 4294967295
#        fluentd-sub-second-precision:

volumes:
  server-log:
    driver: local

networks:
  microtube-network:
    name: microtube-network

#  secrets:
#    db-password:
#     file: db/password.txt
