services:
  mysql.db:
    image: mysql:8.0
    restart: on-failure
    command: mysqld --default-authentication-plugin caching_sha2_password
    #    command: [ mysqld, --default-authentication-plugin mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001 ]

    #    user: mysql_user
    #   secrets:
    #     - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-EXAMPLE}
      MYSQL_USER: ${DATABASE_USERNAME:-dbuser}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-abc123}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-abc123}
    expose:
      - 3306
      - 33060
    networks:
      - default
    ports:
      # These ports should be enabled only for development purpose
      - 3306:3306
      - 33060:33060
    healthcheck:
      test: "mysql -h localhost --user=root --password=abc123 -e \"SHOW DATABASES\""
      interval: 20s
      timeout: 10s
      retries: 10

volumes:
  db-data:
    driver: local

#  secrets:
#    db-password:
#     file: db/password.txt
