server:
  port: ${PORT:8080} # Should be kept unchanged if running in container
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:}

api:
  version: v1
  base-path: "/api#{'${api.version:}'.length > 0 ? '/${api.version:}' : ''}"
  server-base-path: "${server.servlet.context-path:}${api.base-path:}"

spring:
  application:
    name: ${APP_NAME:processor-service}
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 2GB
  datasource:
    url: ${MAIN_DB_URL:jdbc:mysql://127.0.0.1:3306/MICROTUBE}
    username: ${MAIN_DB_USERNAME:dbuser}
    password: ${MAIN_DB_PASSWORD:abc123}

  mvc:
    format:
      date-time: iso
  messages: # Alternative config option: create a bean of ReloadableResourceBundleMessageSource
    basename: ${MESSAGES_BASENAME:messages,custom-response-status,errors,error-codes} # name prefix for the file containing message props. Format: config.i18n.messages (dot-separated path names)
    cache-duration: 3600
    encoding: UTF-8

datasource:
  object-store:
    url: ${OBJECT_STORE_URL:http://127.0.0.1:9000}
    username: ${OBJECT_STORE_USERNAME:admin}
    password: ${OBJECT_STORE_PASSWORD:minioadmin}
    bucket:
      temporary: ${OBJECT_STORE_BUCKET_TEMP:temporary}
      hls: ${OBJECT_STORE_BUCKET_HLS:hls}
      avatar: ${OBJECT_STORE_BUCKET_AVATAR:avatar}
      thumbnail: ${OBJECT_STORE_BUCKET_THUMBNAIL:thumbnail}

application:
  jwt:
    secret: ${JWT_SECRET:htfhvoa+IRypMSVcWbp0gWWkir18RCthewNQh/k/cFM=}
    usage-duration: ${JWT_USAGE_DURATION:1800} # Unit: second

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRAR_URL:http://localhost:8761/eureka/}

springdoc:
  swagger-ui:
    path: /swagger-ui.html # Customize swagger-ui path; didn't work?
    enabled: true
    csrf:
      enabled: true
  api-docs:
    version: openapi_3_1
    enabled: true

#fluentd:
#  host: ${FLUENTD_HOST:localhost}
#  port: ${FLUENTD_PORT:24224}

management:
  zipkin:
    tracing:
      export:
        enabled: false

video:
  temp-dir: tmp/original-videos/
  result-dir: tmp/result-videos/
